import type { Metadata } from "next";
import { Merriweather, Open_Sans } from "next/font/google";
import "./globals.css";
import HeaderBar from "@/components/Header/HeaderBar";
import * as React from "react";
import FooterBar from "@/components/Footer/FooterBar";

const merriweather = Merriweather({
  subsets: ['latin'],
  weight: ["300", "400", "700", "900"],
  style: ['normal', 'italic'],
  variable: '--font-merriweather',
});

const openSans = Open_Sans({
  variable: "--font-open-sans",
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "SSG | CIT University",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
} : Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={`font-sans ${merriweather.variable} ${openSans.variable} antialiased`}>
      <HeaderBar/>
      <main className="mt-[120px] min-h-screen">
        {children}
      </main>
      <FooterBar/>
    </body>
    </html>
  );
}
